SWIP-1101 Resolve missing fonts issue (#39)
* SWIP-1101 Script fonts copy from node module dir

* SWIP-1101 Update release yml to include assets

* SWIP-1101 Copy entire assets folder

Remove GOV.UK images and js from repo as we copy them from node modules; keep favicon in pix for Moodle references

* SWIP-1101 Script copy favicons from govuk

* SWIP-1101 Add check for assets in govuk frontend

* Apply Prettier formatting fixes

---------

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -29,15 +29,26 @@ jobs:
         run: npm install
         working-directory: govuk
 
+      - name: Verify govuk-frontend assets exist
+        run: |
+          [ -d govuk/node_modules/govuk-frontend/dist/govuk/assets ] || {
+            echo "GOV.UK Frontend assets missing. Check npm install completed successfully.";
+            exit 1;
+          }  
+
       - name: Compile SCSS to CSS
         run: npm run build:prod
         working-directory: govuk
 
-      - name: Upload compiled govuk/style folder
+      - name: Upload compiled govuk folders
         uses: actions/upload-artifact@v4
         with:
-          name: compiled-govuk-style
-          path: govuk/style
+          name: compiled-govuk
+          path: |
+            govuk/style
+            govuk/assets
+            govuk/javascript
+            govuk/pix
 
   release:
     name: Tag and release
@@ -50,11 +61,11 @@ jobs:
           with: 
             ref: 'main'
 
-        - name: Download compiled govuk folder
+        - name: Download compiled govuk folders
           uses: actions/download-artifact@v4
           with:
-            name: compiled-govuk-style
-            path: govuk/style
+            name: compiled-govuk
+            path: govuk
 
         - name: Create archive    
           run: zip -r 'govuk-moodle-theme.zip' ./govuk
